version: '3'

services:
  sneakersapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: sneakers-docker
    container_name: sneakersapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5.0.0
    container_name: sneakers
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-sneakers
    volumes:
      - ./mongo:/data/db